# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: taisgrupo6unsa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: taisgrupo6examen2
# "service" is the name of this project. This will also be added to your AWS resource names.
service: visualize

stages:
  default:
    params:
      tableName: "products-table-${sls:stage}"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  tableName: 'products-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/products-table-${self:provider.stage}
  environment:
    PRODUCTS_TABLE: ${param:tableName}

functions:
  getProduct:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /products/{proxy+}
          method: GET
  getAllProducts:
    handler: wsgi_handler.handler
    events:
      - http: 
          path: /products
          method: GET
