# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: taisgrupo6unsa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: taisgrupo6examen2
# "service" is the name of this project. This will also be added to your AWS resource names.
service: register-user

stages:
  default:
    params:
      tableUsersName: "users-table-${sls:stage}"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  tableUsersName: 'users-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  apiName: users-api
  runtime: python3.12
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - "*"
  environment:
    USERS_TABLE: ${param:tableUsersName}

functions:
  createUser:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /users
          method: POST
          cors: true
  getUser:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /users/{proxy+}
          method: GET
          cors: true
  getAllUsers:
    handler: wsgi_handler.handler
    events:
      - http: 
          path: /users
          method: GET
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:tableUsersName}
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
