# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fdelgadov
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: taisgrupo6examen2
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auth

stages:
  default:
    params:
      tableName: "employee-users-table-${sls:stage}"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - arn:aws:dynamodb:us-east-1:590183672359:table/employee-users-table-dev/index/UsernameIndex
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: auth
  environment:
    USERS_TABLE: ${param:tableName}
    JWT_SECRET_KEY: fdelgadov

functions:
  auth:
    handler: authorizer.lambda_handler

  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: login
          method: POST
          cors: true
      - http:
          path: users
          method: POST
          cors: true
      - http:
          path: users/{userId}
          method: GET
          authorizer: auth
          cors: true
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:tableName}
